CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS account AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS market AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS trading AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS portfolio AUTHORIZATION admin;
CREATE SCHEMA IF NOT EXISTS accounting AUTHORIZATION admin;