INSERT INTO market.stocks (symbol, name, exchange, status) VALUES
('ACB', 'Ngân hàng TMCP Á Châu', 'HOSE', 'TRADING'),
('BCM', 'Tổng Công ty Đầu tư và Phát triển Công nghiệp', 'HOSE', 'TRADING'),
('BID', 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam', 'HOSE', 'TRADING'),
('BVH', 'Tập đoàn Bảo Việt', 'HOSE', 'TRADING'),
('CTG', 'Ngân hàng TMCP Công Thương Việt Nam', 'HOSE', 'TRADING'),
('FPT', 'Tập đoàn FPT', 'HOSE', 'TRADING'),
('GAS', 'Tổng Công ty Khí Việt Nam', 'HOSE', 'TRADING'),
('GVR', 'Tập đoàn Công nghiệp Cao su Việt Nam', 'HOSE', 'TRADING'),
('HDB', 'Ngân hàng TMCP Phát triển TP.HCM', 'HOSE', 'TRADING'),
('HPG', 'Tập đoàn Hòa Phát', 'HOSE', 'TRADING'),
('MBB', 'Ngân hàng TMCP Quân đội', 'HOSE', 'TRADING'),
('MSN', 'Tập đoàn Masan', 'HOSE', 'TRADING'),
('MWG', 'Công ty CP Đầu tư Thế giới Di động', 'HOSE', 'TRADING'),
('PLX', 'Tập đoàn Xăng dầu Việt Nam', 'HOSE', 'TRADING'),
('POW', 'Tổng Công ty Điện lực Dầu khí Việt Nam', 'HOSE', 'TRADING'),
('SHB', 'Ngân hàng TMCP Sài Gòn - Hà Nội', 'HOSE', 'TRADING'),
('SSB', 'Ngân hàng TMCP Đông Nam Á', 'HOSE', 'TRADING'),
('SSI', 'Công ty CP Chứng khoán SSI', 'HOSE', 'TRADING'),
('STB', 'Ngân hàng TMCP Sài Gòn Thương Tín', 'HOSE', 'TRADING'),
('TCB', 'Ngân hàng TMCP Kỹ thương Việt Nam', 'HOSE', 'TRADING'),
('TPB', 'Ngân hàng TMCP Tiên Phong', 'HOSE', 'TRADING'),
('VCB', 'Ngân hàng TMCP Ngoại thương Việt Nam', 'HOSE', 'TRADING'),
('VHM', 'Công ty CP Vinhomes', 'HOSE', 'TRADING'),
('VIB', 'Ngân hàng TMCP Quốc tế Việt Nam', 'HOSE', 'TRADING'),
('VIC', 'Tập đoàn Vingroup', 'HOSE', 'TRADING'),
('VJC', 'Công ty CP Hàng không Vietjet', 'HOSE', 'TRADING'),
('VNM', 'Công ty CP Sữa Việt Nam', 'HOSE', 'TRADING'),
('VPB', 'Ngân hàng TMCP Việt Nam Thịnh Vượng', 'HOSE', 'TRADING'),
('VRE', 'Công ty CP Vincom Retail', 'HOSE', 'TRADING'),
('LPB', 'Ngân hàng TMCP Lộc Phát Việt Nam', 'HOSE', 'TRADING');