KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="hdx-kafka"
    password="hdx-kafka-secret"
    user_hdx-kafka="hdx-kafka-secret"
    user_hdx-client="hdx-client-secret";
};